title:              Cheeou's Memorandum
email:              best.coder.jiwoo@gmail.com
description:        나의 개발 비망록
author:             cheeou
baseurl:            ""
url:                "https://cheeou.github.io"

# Social Profiles
twitter_username:
github_username:    cheeou
facebook_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-category-pages

